name: horizon
channels:
  - defaults
dependencies:
  - pip:
      - numpy==1.19.5
      - scipy==1.3.0
      - scikit-learn==0.24.2
      - pillow==8.4.0
      - tqdm==4.64.1
      - tensorboardx==2.0
      - opencv-python==4.2.0.32
      - pylsd-nova==1.2.0
      - open3d==0.13.0
      - shapely==1.7.1
    
