// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ0Tgl3ilNKQAKKWazILTGJClHOPkK67c',
    appId: '1:334647849605:web:651176e6f132189b6dafec',
    messagingSenderId: '334647849605',
    projectId: 'lenap-81ff7',
    authDomain: 'lenap-81ff7.firebaseapp.com',
    storageBucket: 'lenap-81ff7.appspot.com',
    measurementId: 'G-Z16E67KRVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQCX2gWIOUa_a3m5b0ezDNk5C5N85w5Hk',
    appId: '1:334647849605:android:7d501af2feb4ca146dafec',
    messagingSenderId: '334647849605',
    projectId: 'lenap-81ff7',
    storageBucket: 'lenap-81ff7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuJmJgMrLqfunN3HbxJuYNZqC1TFp-SUA',
    appId: '1:334647849605:ios:8d19163ef1adb24f6dafec',
    messagingSenderId: '334647849605',
    projectId: 'lenap-81ff7',
    storageBucket: 'lenap-81ff7.appspot.com',
    androidClientId: '334647849605-008645tj9u5novr4nrd9s440nn0tt93j.apps.googleusercontent.com',
    iosClientId: '334647849605-kopoop46mgifeb186jj9u3q7u1fhvabp.apps.googleusercontent.com',
    iosBundleId: 'com.example.lenap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuJmJgMrLqfunN3HbxJuYNZqC1TFp-SUA',
    appId: '1:334647849605:ios:4d2d2735b7e502246dafec',
    messagingSenderId: '334647849605',
    projectId: 'lenap-81ff7',
    storageBucket: 'lenap-81ff7.appspot.com',
    androidClientId: '334647849605-008645tj9u5novr4nrd9s440nn0tt93j.apps.googleusercontent.com',
    iosClientId: '334647849605-ata0e32ich9ci8s5nid8psfv2o7630j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.lenap.RunnerTests',
  );
}
